name: GSI Build

on: [push]

env:
  ROM_URL: https://dl.google.com/developers/android/rvc/images/gsi/aosp_arm64-exp-RPB2.200611.012-6677315.zip
  ROM_NAME: Generic:Android11_B2.5
  ZIP_NAME: Android11_B2.5
  TZ: America/Sao_Paulo
  MIR: gof
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x build/initial.sh
              . build/initial.sh

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'
 
       - name: Install python requirements
         run: |
              pip install pyrogram tgcrypto

       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/HitaloSama/ErfanGSIs.git

       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}
              
         run: |
               chmod +x build/build.sh
               . build/build.sh

       - name: Copy and rename AB build info
         run: cp ErfanGSIs/output/*-AB-*.txt AB.txt

       - name: Print AB build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt

       - name: Send build info to Telegram
         env:
              CHAT_ID: ${{ secrets.CHAT_ID }}
              BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}
         run: |
              python .github/workflows/robot.py
